#1: InvoiceExpress API
ripe-tech/invoice-express-api-js pull request #1
Opened 2021-12-09 17:03 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-invoicing/issues/1 |
| Dependencies | -- |
| Decisions | - Methods to create an invoice, change its status and get a PDF of an invoice. |
| Animated GIF | -- |

2021-12-09 17:49 UTC, joao-conde requested changes

2021-12-09 17:49 UTC, joao-conde commented on README.md
> +UPS API for Javascript is currently licensed under the [Apache License, Version 2.0](http://www.apache.org/licenses/).
Invoice Express API

2021-12-09 17:49 UTC, joao-conde commented on js/base.js
> +        this.invoicingBaseUrl = `https://${this.accountName}.app.invoicexpress.com/`;
Allow override via `kwargs` and delete new line above.

2021-12-09 17:49 UTC, joao-conde commented on js/base.js
> +
Think Joao will want this new line gone

2021-12-09 17:49 UTC, joao-conde commented on js/invoice.js
> +        async createInvoice(payload) {
Add `options` parameter that defaults to `{}` and pass it along to the request (similar to UPS API JS)

2021-12-09 17:49 UTC, joao-conde commented on js/invoice.js
> +        async changeInvoiceStatus(invoiceId, payload) {
Same as above

2021-12-09 17:49 UTC, joao-conde commented on package.json
> +        "yonius": "^0.6.5"
If possible, let's start with upgraded dependencies maybe. At least for yonius (maybe others as well)

2021-12-09 17:49 UTC, joao-conde commented on test/api/base.js
> +        assert.strictEqual(Boolean(api.apiKey), true);
Maybe add one for `assert.strictEqual(Boolean(api.invoiceBaseUrl), true);`
Also, maybe test for `api.accountName === "name"` and same for key

2021-12-10 16:31 UTC, BeeMargarida commented
@joao-conde Just pinging to remind you abot this

2021-12-10 16:35 UTC, joao-conde approved these changes

2021-12-14 09:47 UTC, joamag approved these changes

2021-12-14 09:47 UTC, merged